version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flag-engine-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: flaguser
      POSTGRES_PASSWORD: flagpass
      POSTGRES_DB: flag_engine
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
